var start = [
  [{
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }],
  [{
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }],
  [{
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }],
  [{
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }],
  [{
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }],
  [{
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }, {
    tile: 'grass',
    walk: true,
    teleport: false
  }],
];